# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-05 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_auto_20160504_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='organization',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='organization',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='voting.Organization'),
        ),
    ]
