# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-05 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_auto_20160505_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='organization',
            field=models.ManyToManyField(blank=True, related_name='users', to='voting.Organization'),
        ),
    ]
