# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-18 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_auto_20160505_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='state',
            field=models.CharField(choices=[(b'ACTIVE', b'Activ'), (b'FINISHED', b'Finalizat'), (b'DRAFT', b'Schita')], default='DRAFT', max_length=15),
        ),
    ]
