# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-18 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0009_auto_20160518_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='response',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
