# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-18 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0010_auto_20160518_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='response',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
