# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-18 21:31
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0012_auto_20160518_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='response',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set([('user', 'campaign')]),
        ),
    ]
