# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-18 21:33
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0013_auto_20160518_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='response',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
